INSERT [ORNG.].[Apps] VALUES(10,'Featured Presentations','http://stage-profiles.ucsf.edu/apps_200/RDFTest.xml',NULL,0);
INSERT [ORNG.].[Apps] VALUES(101,'Featured Presentations','http://stage-profiles.ucsf.edu/apps_200/SlideShare.xml',NULL,1);
INSERT [ORNG.].[Apps] VALUES(102,'Faculty Mentoring','http://stage-profiles.ucsf.edu/apps_200/Mentor.xml',NULL,0);
 INSERT [ORNG.].[Apps] VALUES(103,'Websites','http://stage-profiles.ucsf.edu/apps_200/Links.xml',NULL,1);
INSERT [ORNG.].[Apps] VALUES(104,'Profile List Tool','http://stage-profiles.ucsf.edu/apps_200/ProfileListTool.xml',NULL,1);
INSERT [ORNG.].[Apps] VALUES(112,'Twitter','http://stage-profiles.ucsf.edu/apps_200/Twitter.xml',NULL,1);
INSERT [ORNG.].[Apps] VALUES(114,'Featured Videos','http://stage-profiles.ucsf.edu/apps_200/YouTube.xml',NULL,1);

INSERT [ORNG.].[AppViews] VALUES(101,'edit/default.aspx','home','gadgets-edit','Public',4, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':1, ''closed_width'':700}' );
INSERT [ORNG.].[AppViews] VALUES(101,'profile/display.aspx','profile','gadgets-view','RegistryDefined',4, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':0, ''closed_width'':330}' );
INSERT [ORNG.].[AppViews] VALUES(102,'edit/default.aspx','home','gadgets-edit','Public',5, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':1, ''closed_width'':700}' );
-INSERT [ORNG.].[AppViews] VALUES(102,'profile/display.aspx','profile','gadgets-view','RegistryDefined',5, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':0, ''closed_width'':330}' );
INSERT [ORNG.].[AppViews] VALUES(103,'edit/default.aspx','home','gadgets-edit','Public',1, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':1, ''closed_width'':700}' );
INSERT [ORNG.].[AppViews] VALUES(103,'profile/display.aspx','profile','gadgets-view','RegistryDefined',1, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':0, ''closed_width'':330}' );
INSERT [ORNG.].[AppViews] VALUES(104,'search/default.aspx','small','gadgets-tools','Users',10, NULL);
INSERT [ORNG.].[AppViews] VALUES(104,'profile/display.aspx','small','gadgets-tools','Users',10, NULL);
INSERT [ORNG.].[AppViews] VALUES(104,'orng/gadgetdetails.aspx','canvas','gadgets-detail','Users',10, NULL);
INSERT [ORNG.].[AppViews] VALUES(112,'edit/default.aspx','home','gadgets-edit','Public',8, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':1, ''closed_width'':700}' );
INSERT [ORNG.].[AppViews] VALUES(112,'profile/display.aspx','profile','gadgets-view','RegistryDefined',8, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':0, ''closed_width'':330}' );
INSERT [ORNG.].[AppViews] VALUES(114,'edit/default.aspx','home','gadgets-edit','Public',2, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':1, ''closed_width'':700}' );
INSERT [ORNG.].[AppViews] VALUES(114,'profile/display.aspx','profile','gadgets-view','RegistryDefined',2, '{''gadget_class'':''ORNGToggleGadget'', ''start_closed'':0, ''closed_width'':330}' );
