//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profiles.ORCID {
    
    
    public partial class CreationConfirmation {
        
        /// <summary>
        /// CreationConfirmation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Profiles.ORCID.Modules.CreationConfirmation.CreationConfirmation CreationConfirmation1;
    }
}
