/*  
 
    Copyright (c) 2008-2010 by the President and Fellows of Harvard College. All rights reserved.  
    Profiles Research Networking Software was developed under the supervision of Griffin M Weber, MD, PhD.,
    and Harvard Catalyst: The Harvard Clinical and Translational Science Center, with support from the 
    National Center for Research Resources and Harvard University.


    Code licensed under a BSD License. 
    For details, see: LICENSE.txt 
  
*/







using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Connects.Profiles.Service.DataContracts
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://connects.profiles.schema/profiles/query")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://connects.profiles.schema/profiles/query", IsNullable = true)]
    [DataContract(Namespace = "http://connects.profiles.schema/profiles/query", Name = "Profiles")]
    public partial class Profiles
    {

        private QueryDefinition queryDefinitionField;

        private OutputOptions outputOptionsField;

        private ProfilesOperation operationField;

        private int operationVersion;


        [DataMember(IsRequired = true, Name = "QueryDefinition", Order = 0)]
        public QueryDefinition QueryDefinition
        {
            get
            {
                return this.queryDefinitionField;
            }
            set
            {
                this.queryDefinitionField = value;
            }
        }

        [DataMember(IsRequired = false, Name = "OutputOptions", Order = 1)]
        public OutputOptions OutputOptions
        {
            get
            {
                return this.outputOptionsField;
            }
            set
            {
                this.outputOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = true, Name = "Operation", Order = 2)]
        public ProfilesOperation Operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = true, Name = "Version", Order = 3)]
        public int Version
        {
            set
            {

                operationVersion = value;
            }
            get
            {

                return operationVersion;
            }


        }






    }

    /// <remarks/>        
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "QueryDefinition")]
    public partial class QueryDefinition
    {
        private string queryIDField;

        private string personIDField;

        private Name nameField;

        private PersonFilterList personFilterListField;

        private InternalIDList internalIdListField;

        private AffiliationList affiliationListField;

        private FacultyRankList facultyRankListField;

        private Keywords keywordsField;


        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "string")]
        [DataMember(IsRequired = false, Name = "QueryID", Order = 1)]
        public string QueryID
        {
            get
            {
                return this.queryIDField;
            }
            set
            {
                this.queryIDField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "PersonID", Order = 2)]
        public string PersonID
        {
            get
            {
                return this.personIDField;
            }
            set
            {
                this.personIDField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "Name", Order = 3)]
        public Name Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "PersonFilterList", Order = 4)]
        public PersonFilterList PersonFilterList
        {
            get
            {
                return this.personFilterListField;
            }
            set
            {
                this.personFilterListField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "InternalIDList", Order = 5)]
        public InternalIDList InternalIDList
        {
            get
            {
                return this.internalIdListField;
            }
            set
            {
                this.internalIdListField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "AffiliationList", Order = 6)]
        public AffiliationList AffiliationList
        {
            get
            {
                return this.affiliationListField;
            }
            set
            {
                this.affiliationListField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "FacultyRankList", Order = 7)]
        public FacultyRankList FacultyRankList
        {
            get
            {
                return this.facultyRankListField;
            }
            set
            {
                this.facultyRankListField = value;
            }
        }

        /// <remarks/>
        [DataMember(IsRequired = false, Name = "Keywords", Order = 8)]
        public Keywords Keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "Name")]
    public partial class Name
    {

        private LastName lastNameField;

        private FirstName firstNameField;

        [DataMember(IsRequired = false, Name = "LastName", Order = 1)]
        public LastName LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        [DataMember(IsRequired = false, Name = "FirstName", Order = 2)]
        public FirstName FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "LastName")]
    public partial class LastName
    {

        private NameMatchType matchTypeField;

        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "MatchType", Order = 1)]
        public NameMatchType MatchType
        {
            get
            {
                return this.matchTypeField;
            }
            set
            {
                this.matchTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [DataMember(IsRequired = false, Name = "Text", Order = 3)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "NameMatchType")]
    public enum NameMatchType
    {
        [EnumMemberAttribute(Value = "left")]
        left,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "OutputOptions")]
    public partial class OutputOptions
    {

        private OutputOptionsSortType sortTypeField;

        private string startRecordField;

        private string maxRecordsField;

        private string sortAscField;

        private OutputFilterList outputFilterListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "SortType", Order = 1)]
        public OutputOptionsSortType SortType
        {
            get
            {
                return this.sortTypeField;
            }
            set
            {
                this.sortTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [DataMember(IsRequired = false, Name = "StartRecord", Order = 2)]
        public string StartRecord
        {
            get
            {
                return this.startRecordField;
            }
            set
            {
                this.startRecordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [DataMember(IsRequired = false, Name = "MaxRecords", Order = 3)]
        public string MaxRecords
        {
            get
            {
                return this.maxRecordsField;
            }
            set
            {
                this.maxRecordsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "string")]
        [DataMember(IsRequired = false, Name = "SortAsc", Order = 4)]
        public string SortAsc
        {
            get
            {
                return this.sortAscField;
            }
            set
            {
                this.sortAscField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputFilterList")]
        [DataMember(IsRequired = false, Name = "OutputFilterList", Order = 5)]
        public OutputFilterList OutputFilterList
        {
            get
            {
                return this.outputFilterListField;
            }
            set
            {
                this.outputFilterListField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "OutputOptionsSortType")]
    public enum OutputOptionsSortType
    {
        [EnumMemberAttribute(Value = "QueryRelevance")]
        QueryRelevance,

        [EnumMemberAttribute(Value = "LastFirstName")]
        LastFirstName,

        [EnumMemberAttribute(Value = "Institution_Fullname")]
        Institution_Fullname,

        [EnumMemberAttribute(Value = "Department")]
        Department,

        [EnumMemberAttribute(Value = "Publications")]
        Publications,

        [EnumMemberAttribute(Value = "FacultyRank")]
        FacultyRank,

        [EnumMemberAttribute(Value = "PersonId")]
        PersonId,

        [EnumMemberAttribute(Value = "Division")]
        Division,
    }

    /// <remarks/>
    public partial class Keywords
    {
        private KeywordString keywordStringList;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        [DataMember(IsRequired = false, Name = "KeywordString")]
        public KeywordString KeywordString
        {
            get
            {
                return this.keywordStringList;
            }
            set
            {
                this.keywordStringList = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class KeywordString
    {

        private KeywordMatchType matchTypeField;
        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "MatchType", Order = 1)]
        public KeywordMatchType MatchType
        {
            get
            {
                return this.matchTypeField;
            }
            set
            {
                this.matchTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [DataMember(IsRequired = false, Name = "Text")]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "KeywordMatchType")]
    public enum KeywordMatchType
    {
        [EnumMemberAttribute(Value = "and")]
        and,

        [EnumMemberAttribute(Value = "exact")]
        exact,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "FacultyRankList")]
    public partial class FacultyRankList
    {

        private List<string> facultyRankField;

        private bool excludeVisitingField;

        private bool excludeFullTimeField;

        private bool excludeEmeritusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FacultyRank")]
        [DataMember(IsRequired = false, Name = "FacultyRank", Order = 1)]
        public List<string> FacultyRank
        {
            get
            {
                return this.facultyRankField;
            }
            set
            {
                this.facultyRankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "ExcludeVisiting", Order = 2)]
        public bool ExcludeVisiting
        {
            get
            {
                return this.excludeVisitingField;
            }
            set
            {
                this.excludeVisitingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "ExcludeFullTime", Order = 3)]
        public bool ExcludeFullTime
        {
            get
            {
                return this.excludeFullTimeField;
            }
            set
            {
                this.excludeFullTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "ExcludeEmeritus", Order = 4)]
        public bool ExcludeEmeritus
        {
            get
            {
                return this.excludeEmeritusField;
            }
            set
            {
                this.excludeEmeritusField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    //[System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute()]
    //[DataContract(Name = "FacultyRank")]
    //public enum FacultyRank
    //{
    //    [System.Xml.Serialization.XmlEnumAttribute("Full Professor")]
    //    [EnumMember(Value = "Full Professor")]
    //    FullProfessor,

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlEnumAttribute("Associate Professor")]
    //    [EnumMember(Value = "Associate Professor")]
    //    AssociateProfessor,

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlEnumAttribute("Assistant Professor")]
    //    [EnumMember(Value = "Assistant Professor")]
    //    AssistantProfessor,

    //    [EnumMember(Value = "Lecturer")]
    //    Lecturer,

    //    [EnumMember(Value = "Instructor")]
    //    Instructor,

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlEnumAttribute("Fellow or Post Doc")]
    //    [EnumMember(Value = "Fellow or Post Doc")]
    //    FelloworPostDoc,

    //    [System.Xml.Serialization.XmlEnumAttribute("Other Faculty")]
    //    [EnumMember(Value = "Other Faculty")]
    //    OtherFaculty,

    //    [System.Xml.Serialization.XmlEnumAttribute("Research Assistant")]
    //    [EnumMember(Value = "Research Assistant")]
    //    ResearchAssistant,


    //    [System.Xml.Serialization.XmlEnumAttribute("")]
    //    [EnumMember(Value = " ")]
    //    Nothing,

    //}

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "FirstName")]
    public partial class FirstName
    {

        private NameMatchType matchTypeField;

        private bool matchTypeFieldSpecified;

        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(IsRequired = false, Name = "MatchType", Order = 1)]
        public NameMatchType MatchType
        {
            get
            {
                return this.matchTypeField;
            }
            set
            {
                this.matchTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember(IsRequired = false, Name = "MatchTypeSpecified", Order = 2)]
        public bool MatchTypeSpecified
        {
            get
            {
                return this.matchTypeFieldSpecified;
            }
            set
            {
                this.matchTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [DataMember(IsRequired = false, Name = "Text", Order = 3)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    [DataContract(Name = "ProfilesOperation")]
    public enum ProfilesOperation
    {
        [EnumMember(Value = "GetPersonList")]
        GetPersonList,
    }


    ///// <remarks/>
    //[System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute()]
    //[DataContract(Name = "ProfilesVersion")]
    //public enum ProfilesVersion
    //{
    //    [EnumMember(Value = "VersionPlaceHolder")]
    //    VersionPlaceHolder,

    //}


}