namespace Profiles.ORCID.Utilities.ProfilesRNSDLL.BO.Interfaces.Profile.Import
{ 
    public partial interface INIHAwards
    { 
        int NIHAwardsID { get; set; } 
        bool NIHAwardsIDIsNull { get; set; }
        int Application_Id { get; set; } 
        bool Application_IdIsNull { get; set; }
        string InternalUsername { get; set; } 
        bool InternalUsernameIsNull { get; set; }
        string Activity { get; set; } 
        bool ActivityIsNull { get; set; }
        string Administering_IC { get; set; } 
        bool Administering_ICIsNull { get; set; }
        int Application_Type { get; set; } 
        bool Application_TypeIsNull { get; set; }
        string ARRA { get; set; } 
        bool ARRAIsNull { get; set; }
        System.DateTime Budget_Start { get; set; } 
        bool Budget_StartIsNull { get; set; }
        System.DateTime Budget_End { get; set; } 
        bool Budget_EndIsNull { get; set; }
        string FOA_Number { get; set; } 
        bool FOA_NumberIsNull { get; set; }
        string Full_Project_Num_DC { get; set; } 
        bool Full_Project_Num_DCIsNull { get; set; }
        int SubProject_Id { get; set; } 
        bool SubProject_IdIsNull { get; set; }
        string Funding_ICs { get; set; } 
        bool Funding_ICsIsNull { get; set; }
        int FY { get; set; } 
        bool FYIsNull { get; set; }
        string IC_Name { get; set; } 
        bool IC_NameIsNull { get; set; }
        string NIH_Reporting_Categories { get; set; } 
        bool NIH_Reporting_CategoriesIsNull { get; set; }
        string Org_City { get; set; } 
        bool Org_CityIsNull { get; set; }
        string Org_Country { get; set; } 
        bool Org_CountryIsNull { get; set; }
        string Org_Dept { get; set; } 
        bool Org_DeptIsNull { get; set; }
        int Org_District { get; set; } 
        bool Org_DistrictIsNull { get; set; }
        string Org_DUNS { get; set; } 
        bool Org_DUNSIsNull { get; set; }
        string Org_FIPS { get; set; } 
        bool Org_FIPSIsNull { get; set; }
        string Org_State { get; set; } 
        bool Org_StateIsNull { get; set; }
        string Org_ZipCode { get; set; } 
        bool Org_ZipCodeIsNull { get; set; }
        string Organization { get; set; } 
        bool OrganizationIsNull { get; set; }
        string PI_Names { get; set; } 
        bool PI_NamesIsNull { get; set; }
        string PI_PersonIds { get; set; } 
        bool PI_PersonIdsIsNull { get; set; }
        System.DateTime Project_Start { get; set; } 
        bool Project_StartIsNull { get; set; }
        System.DateTime Project_End { get; set; } 
        bool Project_EndIsNull { get; set; }
        string Project_Num { get; set; } 
        bool Project_NumIsNull { get; set; }
        string Project_Terms { get; set; } 
        bool Project_TermsIsNull { get; set; }
        string Project_Title { get; set; } 
        bool Project_TitleIsNull { get; set; }
        string Relevance { get; set; } 
        bool RelevanceIsNull { get; set; }
        int Serial_Number { get; set; } 
        bool Serial_NumberIsNull { get; set; }
        string Study_Section { get; set; } 
        bool Study_SectionIsNull { get; set; }
        string Study_Section_Name { get; set; } 
        bool Study_Section_NameIsNull { get; set; }
        string Suffix { get; set; } 
        bool SuffixIsNull { get; set; }
        int Support_Year { get; set; } 
        bool Support_YearIsNull { get; set; }
        int Total_Cost { get; set; } 
        bool Total_CostIsNull { get; set; }
        int Total_Cost_Sub_Project { get; set; } 
        bool Total_Cost_Sub_ProjectIsNull { get; set; }
        int ImportID { get; set; } 
        bool ImportIDIsNull { get; set; }
        string Major_Component_Name { get; set; } 
        bool Major_Component_NameIsNull { get; set; }
        System.DateTime Award_Notice_Date { get; set; } 
        bool Award_Notice_DateIsNull { get; set; }
        string Core_Project_Num { get; set; } 
        bool Core_Project_NumIsNull { get; set; }
        string CFDA_Code { get; set; } 
        bool CFDA_CodeIsNull { get; set; }
        string Ed_Inst_Type { get; set; } 
        bool Ed_Inst_TypeIsNull { get; set; }
        string Program_Officer_Name { get; set; } 
        bool Program_Officer_NameIsNull { get; set; }
        string PHR { get; set; } 
        bool PHRIsNull { get; set; }
        bool IsBU { get; set; } 
        bool IsBUIsNull { get; set; }
        bool IsBUMC { get; set; } 
        bool IsBUMCIsNull { get; set; }
        bool IsBMC { get; set; } 
        bool IsBMCIsNull { get; set; }
        int PubCount { get; set; } 
        bool PubCountIsNull { get; set; }
    } 
} 
