@echo off

type CopyrightNotice.txt
type EnableFullTextSearch.sql

type Utility.NLP.Schema.sql
type Utility.Math.Schema.sql
type Utility.Application.Schema.sql
type User.Session.Schema.sql
type User.Account.Schema.sql
type Search.Framework.Schema.sql
type Search.Cache.Schema.sql
type Search..Schema.sql
type RDF.Stage.Schema.sql
type RDF.SemWeb.Schema.sql
type RDF.Security.Schema.sql
type RDF.Search.Schema.sql
type RDF.Cache.Schema.sql
type RDF..Schema.sql
type Profile.Module.Schema.sql
type Profile.Import.Schema.sql
type Profile.Framework.Schema.sql
type Profile.Data.Schema.sql
type Profile.Cache.Schema.sql
type Ontology.Presentation.Schema.sql
type Ontology.Import.Schema.sql
type Ontology..Schema.sql
type Module.Profile.Schema.sql
type Module.Edit.Schema.sql
type Module.Beta.Schema.sql
type Login.Framework.Schema.sql
type History.Framework.Schema.sql
type History.Schema.sql
type Framework..Schema.sql
type Edit.Module.Schema.sql
type Edit.Framework.Schema.sql
type Direct.Framework.Schema.sql
type Direct..Schema.sql

type ft.FullTextCatalog.sql

type Profile.Import.Person.Table.sql
type Profile.Data.Person.Table.sql
type Profile.Cache.Person.Table.sql
type Profile.Data.Person.Affiliation.Table.sql
type Profile.Cache.Person.Affiliation.Table.sql
type Direct..LogOutgoing.Table.sql
type Direct..LogIncoming.Table.sql
type RDF.Stage.Log.Triple.Table.sql
type Framework..Log.Job.Table.sql
type RDF.Stage.Log.DataMap.Table.sql
type Ontology..Namespace.Table.sql
type Utility.Math.N.Table.sql
type RDF.Security.Member.Table.sql
type Utility.NLP.ParsePorterStemming.Table.sql
type Framework..Parameter.Table.sql
type Ontology.Presentation.Panel.Table.sql
type Ontology.Import.OWL.Table.sql
type Profile.Data.Organization.Institution.Table.sql
type Search.Cache.History.TopSearchPhrase.Table.sql
type User.Session.History.ResolveURL.Table.sql
type Search..History.Query.Table.sql
type Search..History.Phrase.Table.sql
type RDF.Security.Group.Table.sql
type Framework..JobGroup.Table.sql
type Framework..Job.Table.sql
type RDF.Stage.InternalNodeMap.Table.sql
type Framework..InstallData.Table.sql
type Profile.Data.Organization.Division.Table.sql
type Profile.Data.Organization.Department.Table.sql
type RDF.Security.NodeProperty.Table.sql
type RDF..Node.Table.sql
type User.Account.DesignatedProxy.Table.sql
type User.Account.DefaultProxy.Table.sql
type Ontology..DataMap.Table.sql
type Ontology.Presentation.General.Table.sql
type Profile.Data.Concept.Mesh.XML.Table.sql
type Profile.Cache.Concept.Mesh.Word2meshAll.Table.sql
type Profile.Cache.Concept.Mesh.Word2Mesh3All.Table.sql
type Profile.Cache.Concept.Mesh.Word2mesh3.Table.sql
type Profile.Cache.Concept.Mesh.Word2mesh2All.Table.sql
type Profile.Cache.Concept.Mesh.Word2mesh2.Table.sql
type Profile.Cache.Concept.Mesh.Word2mesh.Table.sql
type User.Session.Bot.Table.sql
type Profile.Cache.Concept.Mesh.Journal.Table.sql
type Profile.Data.Concept.Mesh.TreeTop.Table.sql
type Profile.Cache.Concept.Mesh.TreeTop.Table.sql
type Profile.Data.Concept.Mesh.Tree.Table.sql
type Profile.Cache.Concept.Mesh.Tree.Table.sql
type Profile.Data.Concept.Mesh.Term.Table.sql
type Profile.Cache.Concept.Mesh.SimilarConcept.Table.sql
type Profile.Data.Concept.Mesh.SemanticType.Table.sql
type Profile.Data.Concept.Mesh.SemanticGroupType.Table.sql
type Profile.Data.Concept.Mesh.SemanticGroup.Table.sql
type Profile.Data.Concept.Mesh.Qualifier.Table.sql
type Profile.Cache.Concept.Mesh.PersonPublication.Table.sql
type Profile.Cache.Concept.Mesh.Person.Table.sql
type Ontology..ClassTreeDepth.Table.sql
type Ontology..ClassProperty.Table.sql
type Ontology..ClassGroupClass.Table.sql
type Ontology..ClassGroup.Table.sql
type Profile.Data.Concept.Mesh.File.Table.sql
type Profile.Data.Concept.Mesh.Descriptor.Table.sql
type Profile.Cache.Concept.Mesh.Count.Table.sql
type RDF..Alias.Table.sql
type Profile.Import.Beta.Narrative.Table.sql
type Profile.Import.Beta.DisplayPreference.Table.sql
type Profile.Import.Beta.Award.Table.sql
type User.Account.Relationship.Table.sql
type Profile.Data.Publication.Type.Table.sql
type Profile.Data.Publication.Pubmed.Journal.Table.sql
type Profile.Data.Publication.PubMed.General.Table.sql
type Profile.Data.Publication.PubMed.DisambiguationAudit.Table.sql
type Profile.Data.Publication.PubMed.DisambiguationAffiliation.Table.sql
type Profile.Data.Publication.PubMed.Disambiguation.Table.sql
type Profile.Data.Publication.PubMed.AllXML.Table.sql
type Profile.Cache.Publication.PubMed.AuthorPosition.Table.sql
type Profile.Data.Publication.MyPub.Category.Table.sql
type Profile.Data.Publication.ISI.PubGeneral.Table.sql
type Profile.Data.Publication.ISI.MPID.Table.sql
type Profile.Data.Publication.Entity.InformationResource.Table.sql
type Profile.Data.Publication.Entity.Authorship.Table.sql
type Profile.Data.Publication.DSpace.PubGeneral.Table.sql
type Profile.Data.Publication.DSpace.MPID.Table.sql
type Search.Cache.Public.NodeSummary.Table.sql
type Search.Cache.Public.NodeRDF.Table.sql
type Search.Cache.Public.NodePrefix.Table.sql
type Search.Cache.Public.NodeMap.Table.sql
type Search.Cache.Public.NodeExpand.Table.sql
type Search.Cache.Public.NodeClass.Table.sql
type Profile.Import.PersonFilterFlag.Table.sql
type Profile.Import.PersonAffiliation.Table.sql
type Profile.Cache.Process.Audit.Table.sql
type Ontology..PropertyGroupProperty.Table.sql
type Ontology..PropertyGroup.Table.sql
type Search.Cache.Private.NodeSummary.Table.sql
type Search.Cache.Private.NodeRDF.Table.sql
type Search.Cache.Private.NodePrefix.Table.sql
type Search.Cache.Private.NodeMap.Table.sql
type Search.Cache.Private.NodeExpand.Table.sql
type Search.Cache.Private.NodeClass.Table.sql
type Profile.Data.Person.Filter.Table.sql
type Profile.Data.Person.FacultyRank.Table.sql
type Profile.Cache.Person.SimilarPerson.Table.sql
type Profile.Cache.Person.PhysicalNeighbor.Table.sql
type Profile.Cache.SNA.Coauthor.Reach.Table.sql
type Profile.Cache.SNA.Coauthor.DistanceLog.Table.sql
type Profile.Cache.SNA.Coauthor.Distance.Table.sql
type Profile.Cache.SNA.Coauthor.Betweenness.Table.sql
type Profile.Cache.SNA.Coauthor.Table.sql
type Direct..Sites.Table.sql
type RDF.Stage.Triple.Map.Table.sql
type RDF.Stage.Triple.Table.sql
type RDF..Triple.Table.sql
type Ontology.Import.Triple.Table.sql
type Utility.NLP.Thesaurus.Source.Table.sql
type Utility.NLP.Thesaurus.Table.sql
type Profile.Module.Support.Map.Table.sql
type Profile.Module.Support.HTML.Table.sql
type User.Account.User.Table.sql
type Profile.Import.User.Table.sql
type Utility.NLP.StopWord.Table.sql
type Framework..RestPath.Table.sql
type Ontology.Presentation.XML.Table.sql
type User.Session.Session.Table.sql
type Profile.Data.Publication.PubMed.Author.Table.sql
type Profile.Data.Publication.PubMed.PubType.Table.sql
type Profile.Data.Publication.PubMed.Keyword.Table.sql
type Profile.Data.Person.Photo.Table.sql
type Profile.Data.Person.FilterRelationship.Table.sql
type Profile.Data.Publication.Person.Exclude.Table.sql
type Profile.Data.Publication.Person.Add.Table.sql
type Profile.Data.Publication.PubMed.Accession.Table.sql
type Profile.Data.Publication.MyPub.General.Table.sql
type Profile.Data.Publication.PubMed.Databank.Table.sql
type Profile.Data.Publication.PubMed.Chemical.Table.sql
type Profile.Data.Publication.PubMed.Mesh.Table.sql
type Profile.Data.Publication.PubMed.Investigator.Table.sql
type Profile.Data.Publication.PubMed.Grant.Table.sql
type Profile.Data.Publication.PubMed.Author2Person.Table.sql
type Profile.Data.Publication.Person.Include.Table.sql

type RDF..fnTripleHash.UserDefinedFunction.sql
type Utility.Application.fnText2Bool.UserDefinedFunction.sql
type Utility.NLP.fnPorterEndsDoubleConsonant.UserDefinedFunction.sql
type Utility.Application.fnBool2Text.UserDefinedFunction.sql
type Utility.Application.fnBinaryToBase64.UserDefinedFunction.sql
type Utility.Application.fnBase64ToBinary.UserDefinedFunction.sql
type Utility.Application.fnExecDynamicXQuery.UserDefinedFunction.sql
type Utility.Application.fnEncryptRC4.UserDefinedFunction.sql
type Utility.NLP.fnPorterCVCpattern.UserDefinedFunction.sql
type Profile.Data.fnPublication.Pubmed.GetPubDate.UserDefinedFunction.sql
type Profile.Cache.fnPublication.Pubmed.General2Reference.UserDefinedFunction.sql
type Utility.NLP.fnNormalize.UserDefinedFunction.sql
type Utility.NLP.fnNamePart1.UserDefinedFunction.sql
type RDF.SemWeb.fnHash2Base64.UserDefinedFunction.sql
type RDF..fnValueHash.UserDefinedFunction.sql
type RDF..fnURI2NodeID.UserDefinedFunction.sql
type Ontology.Import.fnGetPropertyTree.UserDefinedFunction.sql
type Ontology.Import.fnGetClassTree.UserDefinedFunction.sql
type Utility.NLP.fnPorterCountm.UserDefinedFunction.sql
type Utility.NLP.fnPorterContainsVowel.UserDefinedFunction.sql
type Utility.Application.fnEncryptBase64RC4.UserDefinedFunction.sql
type Utility.Application.fnDecryptBase64RC4.UserDefinedFunction.sql
type Utility.NLP.fnPorterEndsCVC.UserDefinedFunction.sql
type Utility.NLP.fnPorterEndsDoubleCVC.UserDefinedFunction.sql
type Utility.NLP.fnPorterStep5.UserDefinedFunction.sql
type Utility.NLP.fnPorterStep4.UserDefinedFunction.sql
type Utility.NLP.fnPorterStep3.UserDefinedFunction.sql
type Utility.NLP.fnPorterStep2.UserDefinedFunction.sql
type Utility.NLP.fnPorterStep1.UserDefinedFunction.sql
type Profile.Data.fnPublication.Person.GetPublications.UserDefinedFunction.sql
type Utility.NLP.fnPorterAlgorithm.UserDefinedFunction.sql
type Utility.NLP.fnNormalizeSplitStem.UserDefinedFunction.sql
type Utility.NLP.fnQuoteNormalizeSplitStem.UserDefinedFunction.sql

type Framework..vwBufferObjects.View.sql
type Framework..vwBufferDatabases.View.sql
type Framework..vwDatabaseObjects.View.sql
type RDF.SemWeb.vwPublic_Entities.View.sql
type Profile.Data.vwPublication.Entity.Authorship.View.sql
type RDF.SemWeb.vwPublic_Statements.View.sql
type Framework..vwDatabaseCode.View.sql
type Profile.Cache.vwConcept.Mesh.Person.View.sql
type RDF.SemWeb.vwPrivate_Entities.View.sql
type Profile.Data.vwPerson.SecurityGroup.View.sql
type RDF.SemWeb.vwHash2Base64.View.sql
type RDF.SemWeb.vwPrivate_Statements.View.sql
type Profile.Data.vwPublication.Entity.InformationResource.View.sql
type RDF..vwTripleValue.View.sql
type RDF..vwBigDataTriple.View.sql
type Profile.Data.vwPerson.Affiliation.View.sql
type Profile.Data.vwPerson.View.sql
type Ontology.Import.vwOwlTriple.View.sql
type Profile.Data.vwPublication.Pubmed.Mesh.Descriptor.View.sql
type Profile.Data.vwPublication.Entity.General.View.sql
type Profile.Data.vwPublication.Entity.Concept.MinorTopicList.View.sql
type Profile.Data.vwPublication.Entity.Concept.MajorTopicList.View.sql
type Profile.Data.vwPublication.Entity.Concept.View.sql
type RDF..vwPropertyTall.View.sql
type Ontology..vwPropertyTall.View.sql
type RDF.SemWeb.vwPrivate_Literals.View.sql
type Profile.Data.vwPerson.Photo.View.sql
type RDF..vwClass.View.sql
type RDF.SemWeb.vwPublic_Literals.View.sql
type RDF..vwPropertyWide.View.sql
type Ontology..vwPropertyWide.View.sql
type Ontology..vwMissingPropertyGroupProperty.View.sql
type Ontology..vwMissingClassProperty.View.sql

type PresentationXML.SqlAssembly.sql

type Framework..LoadXMLFile.StoredProcedure.sql
type Framework..LICENCE.StoredProcedure.sql
type User.Account.Proxy.Search.StoredProcedure.sql
type Edit.Framework.ResolveURL.StoredProcedure.sql
type Direct.Framework.ResolveURL.StoredProcedure.sql
type History.Framework.ResolveURL.StoredProcedure.sql
type Search.Framework.ResolveURL.StoredProcedure.sql
type Profile.Data.Person.DoesPersonExist.StoredProcedure.sql
type Profile.Cache.SNA.Coauthor.UpdateBetweenness.StoredProcedure.sql
type Profile.Import.ValidateProfilesImportTables.StoredProcedure.sql
type Framework..RunJobGroup.StoredProcedure.sql
type Profile.Framework.ResolveURL.StoredProcedure.sql
type Profile.Cache.SNA.Coauthor.UpdateSummary.StoredProcedure.sql
type Utility.NLP.UpdateThesaurus.StoredProcedure.sql
type Profile.Module.Support.GetHTML.StoredProcedure.sql
type Framework..ResolveURL.StoredProcedure.sql
type Profile.Data.Person.GetUnGeocodedAddresses.StoredProcedure.sql
type RDF.Stage.ProcessTriples.StoredProcedure.sql
type RDF.Stage.ProcessDataMap.StoredProcedure.sql
type Profile.Cache.Process.AddAuditUpdate.StoredProcedure.sql
type Profile.Data.Person.UpdateUnGeocodedAddress.StoredProcedure.sql
type Profile.Data.Person.GetFilters.StoredProcedure.sql
type Profile.Data.Person.GetFacultyRanks.StoredProcedure.sql
type Profile.Data.Person.GetAffiliations.StoredProcedure.sql
type Profile.Data.Publication.DoesPublicationExist.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.AddDisambiguationLog.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.AddPMIDs.StoredProcedure.sql
type User.Account.Authenticate.StoredProcedure.sql
type Profile.Data.Concept.Mesh.ParseMeshXML.StoredProcedure.sql
type Profile.Data.Concept.Mesh.GetSimilarMesh.StoredProcedure.sql
type Profile.Data.Concept.Mesh.GetJournals.StoredProcedure.sql
type Profile.Data.Concept.Mesh.GetDescriptorXML.StoredProcedure.sql
type Profile.Module.ConnectionDetails.Person.HasResearchArea.GetData.StoredProcedure.sql
type Profile.Module.ConnectionDetails.Person.CoAuthorOf.GetData.StoredProcedure.sql
type Framework..CreateInstallData.StoredProcedure.sql
type Ontology.Presentation.ConvertXML2Tables.StoredProcedure.sql
type Ontology.Import.ConvertTriple2OWL.StoredProcedure.sql
type Profile.Module.NetworkTimeline.Person.HasResearchArea.GetData.StoredProcedure.sql
type Search.Cache.History.UpdateTopSearchPhrase.StoredProcedure.sql
type RDF..GetPropertyList.StoredProcedure.sql
type Search..GetTopSearchPhrase.StoredProcedure.sql
type Profile.Data.Organization.GetInstitutions.StoredProcedure.sql
type Profile.Data.Organization.GetDivisions.StoredProcedure.sql
type Profile.Data.Organization.GetDepartments.StoredProcedure.sql
type RDF.Stage.LoadTriplesFromOntology.StoredProcedure.sql
type Profile.Module.NetworkRadial.GetCoauthors.StoredProcedure.sql
type Profile.Module.NetworkAuthorshipTimeline.Concept.GetData.StoredProcedure.sql
type Ontology..GetClassCounts.StoredProcedure.sql
type Framework..LoadInstallData.StoredProcedure.sql
type RDF.Stage.LoadAliases.StoredProcedure.sql
type Profile.Module.NetworkCloud.Person.HasResearchArea.GetXML.StoredProcedure.sql
type Profile.Module.NetworkCategory.Person.HasResearchArea.GetXML.StoredProcedure.sql
type Profile.Import.LoadProfilesData.StoredProcedure.sql
type RDF.Security.GetSessionSecurityGroupNodes.StoredProcedure.sql
type RDF.Security.GetSessionSecurityGroup.StoredProcedure.sql
type RDF..GetStoreTriple.StoredProcedure.sql
type Ontology.Presentation.ConvertTables2XML.StoredProcedure.sql
type Ontology.Import.ConvertOWL2Triple.StoredProcedure.sql
type Profile.Module.ConnectionDetails.Person.SimilarTo.GetData.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateWord2Mesh.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateTreeTop.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateSimilarConcept.StoredProcedure.sql
type Profile.Module.CustomViewPersonSameDepartment.GetList.StoredProcedure.sql
type RDF..DeleteTriple.StoredProcedure.sql
type Profile.Import.Beta.SetDisplayPreferences.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdatePerson.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateJournal.StoredProcedure.sql
type Profile.Data.Publication.PubMed.GetPersonInfoForDisambiguation.StoredProcedure.sql
type Profile.Data.Publication.PubMed.AddOneAuthorPosition.StoredProcedure.sql
type Profile.Data.Publication.MyPub.GetPublication.StoredProcedure.sql
type Profile.Cache.Person.UpdateAffiliation.StoredProcedure.sql
type Search.Cache.Public.UpdateCache.StoredProcedure.sql
type Profile.Cache.Person.UpdatePhysicalNeighbor.StoredProcedure.sql
type User.Account.Proxy.GetProxies.StoredProcedure.sql
type User.Account.Proxy.DeleteDesignatedProxy.StoredProcedure.sql
type User.Account.Proxy.AddDesignatedProxy.StoredProcedure.sql
type Search.Cache.Private.UpdateCache.StoredProcedure.sql
type Profile.Data.Person.GetPhotos.StoredProcedure.sql
type RDF..SetNodePropertySecurity.StoredProcedure.sql
type User.Account.Relationship.SetRelationship.StoredProcedure.sql
type User.Account.Relationship.GetRelationship.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.ParsePubMedXML.StoredProcedure.sql
type User.Session.UpdateSession.StoredProcedure.sql
type Ontology..UpdateDerivedFields.StoredProcedure.sql
type Ontology..UpdateCounts.StoredProcedure.sql
type Profile.Cache.SNA.Coauthor.UpdateReach.StoredProcedure.sql
type Profile.Cache.SNA.Coauthor.UpdateDistance.StoredProcedure.sql
type Profile.Cache.SNA.Coauthor.UpdateCoauthor.StoredProcedure.sql
type Profile.Data.Person.DeletePhoto.StoredProcedure.sql
type Profile.Cache.Person.UpdateSimilarPerson.StoredProcedure.sql
type Profile.Data.Publication.DeleteOnePublication.StoredProcedure.sql
type Profile.Data.Publication.DeleteAllPublications.StoredProcedure.sql
type Profile.Data.Publication.Entity.UpdateEntityOnePerson.StoredProcedure.sql
type Profile.Data.Publication.Entity.UpdateEntity.StoredProcedure.sql
type Profile.Cache.Person.UpdatePerson.StoredProcedure.sql
type Profile.Data.Publication.GetPersonSharedPublicationsKeyword.StoredProcedure.sql
type Profile.Data.Publication.GetPersonPublications3.StoredProcedure.sql
type Profile.Data.Publication.GetPersonPublications2.StoredProcedure.sql
type Profile.Data.Publication.MyPub.UpdatePublication.StoredProcedure.sql
type Profile.Data.Publication.MyPub.AddPublication.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.AddPubMedXML.StoredProcedure.sql
type Profile.Cache.Publication.PubMed.UpdateAuthorPosition.StoredProcedure.sql
type Profile.Data.Publication.PubMed.GetAllPMIDs.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateCountTree.StoredProcedure.sql
type Profile.Data.Concept.Mesh.GetPublications.StoredProcedure.sql
type Framework..ChangeBaseURI.StoredProcedure.sql
type Ontology..AddProperty.StoredProcedure.sql
type RDF..DeleteNode.StoredProcedure.sql
type Profile.Module.CustomViewAuthorInAuthorship.GetList.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdatePersonPublication.StoredProcedure.sql
type Edit.Module.CustomEditAuthorInAuthorship.GetList.StoredProcedure.sql
type Profile.Module.NetworkTimeline.Person.CoAuthorOf.GetData.StoredProcedure.sql
type RDF..GetStoreNode.StoredProcedure.sql
type RDF..GetDataRDF.StoredProcedure.sql
type RDF..GetPresentationXML.StoredProcedure.sql
type RDF..GetPropertyRangeList.StoredProcedure.sql
type Profile.Module.NetworkMap.GetSimilarPeople.StoredProcedure.sql
type Profile.Module.NetworkMap.GetCoauthors.StoredProcedure.sql
type Profile.Module.NetworkAuthorshipTimeline.Person.GetData.StoredProcedure.sql
type Profile.Data.Person.AddPhoto.StoredProcedure.sql
type Search..ParseSearchString.StoredProcedure.sql
type User.Session.CreateSession.StoredProcedure.sql
type Edit.Module.CustomEditAwardOrHonor.StoreItem.StoredProcedure.sql
type Ontology..CleanUp.StoredProcedure.sql
type Profile.Import.Beta.LoadData.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.LoadDisambiguationResults.StoredProcedure.sql
type Profile.Data.Publication.Pubmed.AddPublication.StoredProcedure.sql
type Profile.Data.Publication.GetPersonPublications.StoredProcedure.sql
type Search.Cache.Public.GetNodes.StoredProcedure.sql
type Search.Cache.Public.GetConnection.StoredProcedure.sql
type Search.Cache.Private.GetNodes.StoredProcedure.sql
type Search.Cache.Private.GetConnection.StoredProcedure.sql
type Profile.Cache.Concept.Mesh.UpdateWord2MeshAll.StoredProcedure.sql
type Search..LookupNodes.StoredProcedure.sql
type Search..GetNodes.StoredProcedure.sql
type Search..GetConnection.StoredProcedure.sql
