SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Framework.].[InstallData](
	[InstallDataID] [int] IDENTITY(0,1) NOT NULL,
	[Data] [xml] NULL,
 CONSTRAINT [PK__InstallData__7CA47C3F] PRIMARY KEY CLUSTERED 
(
	[InstallDataID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
