SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Ontology.].[ClassGroupClass](
	[ClassGroupURI] [varchar](400) NOT NULL,
	[ClassURI] [varchar](400) NOT NULL,
	[SortOrder] [int] NULL,
	[_ClassLabel] [nvarchar](400) NULL,
	[_ClassGroupNode] [bigint] NULL,
	[_ClassNode] [bigint] NULL,
	[_NumberOfNodes] [bigint] NULL,
 CONSTRAINT [PK__ClassGroupClass__31B75ECD] PRIMARY KEY CLUSTERED 
(
	[ClassGroupURI] ASC,
	[ClassURI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [idx_ClassNode] ON [Ontology.].[ClassGroupClass] 
(
	[_ClassNode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
