SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Ontology.].[PropertyGroup](
	[PropertyGroupURI] [varchar](400) NOT NULL,
	[SortOrder] [int] NULL,
	[_PropertyGroupLabel] [nvarchar](400) NULL,
	[_PropertyGroupNode] [bigint] NULL,
	[_NumberOfNodes] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyGroupURI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
