SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Profile.Data].[Publication.DSpace.MPID](
	[MPID] [varchar](50) NOT NULL,
	[PersonID] [int] NULL,
	[DashID] [int] NULL,
 CONSTRAINT [PK__dash2mpid__6E103CD8] PRIMARY KEY CLUSTERED 
(
	[MPID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
