SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Profile.Module].[ProfilesDataAPI.Users](
	[KeyValue] [varchar](100) NOT NULL,
	[Organization] [varchar](100) NULL,
	[ContactName] [varchar](100) NULL,
	[ContactEmail] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[KeyValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
