SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [Profile.Data].[Funding.Role](
	[FundingRoleID] [varchar](50) NOT NULL,
	[PersonID] [int] NULL,
	[FundingAgreementID] [varchar](50) NULL,
	[RoleLabel] [varchar](100) NULL,
	[RoleDescription] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[FundingRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
