SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [Profile.Data].[Funding.Add](
	[FundingRoleID] [varchar](50) NOT NULL,
	[PersonID] [int] NOT NULL,
	[FundingAgreementID] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FundingRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
