CREATE DATABASE [ProfilesVanilla] ON  PRIMARY 
( NAME = N'ProfilesVanilla', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ProfilesVanilla.mdf' , SIZE = 7168KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProfilesVanilla_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ProfilesVanilla_log.ldf' , SIZE = 23872KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ProfilesVanilla] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProfilesVanilla].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProfilesVanilla] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [ProfilesVanilla] SET ANSI_NULLS OFF
GO
ALTER DATABASE [ProfilesVanilla] SET ANSI_PADDING OFF
GO
ALTER DATABASE [ProfilesVanilla] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [ProfilesVanilla] SET ARITHABORT OFF
GO
ALTER DATABASE [ProfilesVanilla] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [ProfilesVanilla] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [ProfilesVanilla] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [ProfilesVanilla] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [ProfilesVanilla] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [ProfilesVanilla] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [ProfilesVanilla] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [ProfilesVanilla] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [ProfilesVanilla] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [ProfilesVanilla] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [ProfilesVanilla] SET  DISABLE_BROKER
GO
ALTER DATABASE [ProfilesVanilla] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [ProfilesVanilla] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [ProfilesVanilla] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [ProfilesVanilla] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [ProfilesVanilla] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [ProfilesVanilla] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [ProfilesVanilla] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [ProfilesVanilla] SET  READ_WRITE
GO
ALTER DATABASE [ProfilesVanilla] SET RECOVERY SIMPLE
GO
ALTER DATABASE [ProfilesVanilla] SET  MULTI_USER
GO
ALTER DATABASE [ProfilesVanilla] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [ProfilesVanilla] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProfilesVanilla', N'ON'
GO
