SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Profile.Data].[Concept.Mesh.SemanticType](
	[DescriptorUI] [varchar](10) NOT NULL,
	[SemanticTypeUI] [varchar](10) NOT NULL,
	[SemanticTypeName] [varchar](50) NULL,
 CONSTRAINT [pk_mesh_semantic_types] PRIMARY KEY CLUSTERED 
(
	[DescriptorUI] ASC,
	[SemanticTypeUI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
