SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Profile.Module].[GenericRDF.Data](
	[Name] [varchar](55) NOT NULL,
	[NodeID] [bigint] NOT NULL,
	[Data] [varchar](max) NULL,
	[SearchableData] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Name] ASC,
	[NodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
