SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Profile.Cache].[SNA.Coauthor.Reach](
	[PersonID] [int] NOT NULL,
	[Distance] [tinyint] NOT NULL,
	[NumPeople] [smallint] NULL,
 CONSTRAINT [PK_sna_reach] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC,
	[Distance] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
