SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [Profile.Data].[List.Member] (
    [ListID]   INT NOT NULL,
    [PersonID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ListID] ASC, [PersonID] ASC)
)

GO
