SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Profile.Module].[Support.Map](
	[SupportMapID] [int] NOT NULL,
	[SupportID] [int] NULL,
	[Institution] [varchar](255) NULL,
	[Department] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SupportMapID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
