SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Profile.Cache].[SNA.Coauthor.DistanceLog](
	[x] [varchar](50) NULL,
	[d] [datetime] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
