SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RDF.Stage].[Triple.Map](
	[StageTripleID] [bigint] NOT NULL,
	[TripleID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StageTripleID] ASC,
	[TripleID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
