SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RDF.Security].[NodeProperty](
	[NodeID] [bigint] NOT NULL,
	[Property] [bigint] NOT NULL,
	[ViewSecurityGroup] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[NodeID] ASC,
	[Property] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
