SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Search.Cache].[Public.NodeMap](
	[NodeID] [bigint] NOT NULL,
	[MatchedByNodeID] [bigint] NOT NULL,
	[Distance] [int] NULL,
	[Paths] [int] NULL,
	[Weight] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[NodeID] ASC,
	[MatchedByNodeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [idx_ms] ON [Search.Cache].[Public.NodeMap] 
(
	[MatchedByNodeID] ASC,
	[NodeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
