SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Search.Cache].[History.TopSearchPhrase](
	[TimePeriod] [char](1) NOT NULL,
	[Phrase] [varchar](100) NOT NULL,
	[NumberOfQueries] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TimePeriod] ASC,
	[Phrase] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
